import type { Filters } from "../models/filters";
import type { GSAPTo } from "../models/gsapFromTo";
import { generateGSAPFromObject } from "./generateGSAPFromObject";
import { getSelectedEasingType } from "./getSelectedEasingType";

/**
 * Generates a GSAPTo object based on the filters provided.
 * The GSAPTo object defines the ending properties of an animation.
 *
 * The ending properties of the animation are generated based on the filters
 * provided and the GSAPFrom object generated by the generateGSAPFromObject
 * function.
 *
 * If a filter is null, the value from the GSAPFrom object is
 * used which means that property won't change during the animation.
 *
 * @param {Filters} filters - The filters object which contains the
 * animation properties and the easing type and speed type.
 * @returns {GSAPTo} - The GSAPTo object which defines the ending
 * properties of an animation.
 */
export const generateGSAPToObject = (filters: Filters) => {
  // Get the selected easing speed types
  const selectedSpeedTypes = getSelectedEasingType(
    filters.easingType
  )?.speedTypes;

  // Produce a string for the easing type based on the filters
  // and whether the easing has speed types
  const easingType = `${filters.easingType}${
    selectedSpeedTypes && selectedSpeedTypes?.length > 0
      ? `.${filters.speedType}`
      : ""
  }`;

  // Generate the GSAP from object
  const gsapFrom = generateGSAPFromObject();

  // If the opacity is greater than 1, multiply it by 0.01
  // to get a value between 0 and 1
  const opacity = filters.animation.opacity ?? gsapFrom.opacity;
  const newOpacity = opacity > 1 ? opacity * 0.01 : opacity;

  // If the scale is greater than 1, multiply it by 0.01
  // to get a value between 0 and 1
  const scale = filters.animation.scale ?? gsapFrom.scale;
  const newScale = scale > 1 ? scale * 0.01 : scale;

  // Generate the GSAP to object
  const gsapTo: GSAPTo = {
    duration: filters.duration,
    ease: easingType,
    x: filters.animation.x ?? gsapFrom.x,
    y: filters.animation.y ?? gsapFrom.y,
    scale: newScale,
    opacity: newOpacity,
    rotate: filters.animation.rotate ?? gsapFrom.rotate,
    skewX: filters.animation.skewX ?? gsapFrom.skewX,
    skewY: filters.animation.skewY ?? gsapFrom.skewY,
  };

  // Return the GSAP to object
  return gsapTo;
};
